### PR TITLE
Adding support for Danish translation.

### PR DESCRIPTION
**Pull request by matsduf**
This is the first step to solve issue #61. The actual translation must be added to this PR.

### CODE REVIEW

**Comment by matsduf** [comment]
@haarbo! More files need translation to Danish. Can you provide the translation in the da.po file in this PR? You could provide it as a PR against the "translation-danish" branch on "matsduf/zonemaster-cli".

**Comment by sandoche2k** [comment]
@matsduf with #61, we will have Danish translation. Ok to merge.

**Comment by matsduf** [comment]
@sandoche2k, should we merge this now, or should we wait for @haarbo to provide the real translation?

**Comment by sandoche2k** [comment]
@matsduf  as per the issue explanation, i think we should merge. For Danish translation, there is #61?

**Pull request merged**
